### ISSUE TITLE
Task list: View this before opening new issues & PRs

### ISSUE THREAD

**Issue by OXY2DEV** [OXY2DEV/markview.nvim#13]
As I have been working on this plugin, I have realized that it's quite lacking.

As such, I am going to completely rewrite it to hopefully make it better(rewrite will be available on the `dev` branch first).

Here's a list of tasks I will do, if it's marked than it means it's completed.

> PRs will not be merged during this period

> Code related tasks

- [x] Provide automatic setup for markdown files
- [x] Make the setup function be callable on the fly(without setting any new autocmds)
- [x] Separate logics into `parser` and `extmarks` into `renderer`
- [ ] Provide `custom_renderer` support 
- [x] Enable style enable & disabling(low priority)
- [x] Make `extmarks` use `inline virtual texts` to reduce cursor jumps and issues with long texts

> Appearance related tasks

- [x] Add more `heading` styles
- [x] Add *proper* title support for callouts
- [x] Make code blocks use specific widths
- [x] Add better styling for links
- [ ] Add support for `video links`
- [x] #20
- [x] Support content alignment in tables

> More tasks will be added in the future

**Comment by OXY2DEV** [comment]
I have some bad news.

![Screenshot_2024-07-02-19-13-21-057_com termux-edit](https://github.com/OXY2DEV/markview.nvim/assets/122956967/f563ce49-37e2-4da1-ad3a-c8b05948c7d4)

I have been made aware that there are some bugs in vim(which were unfortunately inherited by neovim) which makes `conceal` and `nvim_buf_set_extmark()` not work as expected.

This unfortunately **can** affect this plugin and break the previews.

The only good news is, so far it only breaks `code blocks` & `tables`(to a certain degree).

**Comment by OXY2DEV** [comment]
Tasks that were left unchecked will unfortunately not be implemented(either due to technical limitations or not being relevant anymore).

**Comment by OXY2DEV** [comment]
The next update isn't going to be as big.

Here's the current task list.

- [ ] `setext_heading` support will be added
- [ ] Better commands & completion will be added
- [ ] `Concealment` options for some of the options will be given
- [ ] Documentation will be improved
- [ ] Screenshots(???)
- [ ] Probably change some of the defaults(e.g. the `position` in code blocks)
- [ ] Reliance on **soon to be** deprecated will be reduced

And anything relevant from the issues or PRs will be completed (they will appear here).
