### ISSUE TITLE
⚙️ Refactor plugin code

### ISSUE THREAD

**Issue by OXY2DEV** [OXY2DEV/markview.nvim#177]
### ⛳ Goal

Make the code easier to understand, separate different parsers & renderers, provide more control over what gets rendered, make everything easier to maintain & extend etc.

### 📝 Tasks

- [x] Group various configuration options based on their parser/function.
- [x] Provide a good way to modify deeply nested options.
- [x] Fix parsers,
  - [x] Markdown.
  - [x] Markdown inline.
  - [x] LaTeX.
  - [x] HTML.
  - [x] Typst.
  - [x] Yaml
- [x] Fix renderers,
  - [x] Markdown.
  - [x] Markdown inline.
  - [x] LaTeX.
  - [x] HTML.
  - [x] Typst.
  - [x] Yaml
- [x] Improve documentation & code readability.
- [x] Revise `lua patterns` & conditions.
- [x] Revise redraw mechanic(s).
- [x] Fix performance issues on slower devices(e.g. Android).

**Comment by MrGeniusProgrammer** [comment]
@OXY2DEV Thank you for your amazing work. when will this be done?

**Comment by OXY2DEV** [comment]
> @OXY2DEV Thank you for your amazing work. when will this be done?

It really depends on how much time I get. Currently the schedule is a bit tight which is causing slow development speed.

Functionality-wise pretty much everything is ready. I am doing minor changes.

The documentation on the other hand is taking a while.

**Comment by MrGeniusProgrammer** [comment]
> > @OXY2DEV Thank you for your amazing work. when will this be done?
> 
> It really depends on how much time I get. Currently the schedule is a bit tight which is causing slow development speed.
> 
> Functionality-wise pretty much everything is ready. I am doing minor changes.
> 
> The documentation on the other hand is taking a while.

If you need help with the documentation, let me know—I'd be happy to assist.
