### ISSUE TITLE
[BUG] List rendered incorrectly on InsertLeave

### ISSUE THREAD

**Issue by Zeioth** [OXY2DEV/markview.nvim#46]
## Config
* nvim version: 0.10
* theme: default (or any other)
* os: arch linux

```lua
  {
    "OXY2DEV/markview.nvim",
    ft = { "markdown" },
    dependencies = {
      "nvim-treesitter/nvim-treesitter",
      "nvim-tree/nvim-web-devicons"
    },
    opts = {}
  },
```

## What should happen
The unordered list items are converted to bulled points correctly on normal mode.
![screenshot_2024-07-09_13-42-17_988047156](https://github.com/OXY2DEV/markview.nvim/assets/3357792/6d181197-40ae-4de8-a0c5-8230a4267558)

## What actually happen
The bullet points are inserted in the wrong position
![screenshot_2024-07-09_13-40-53_269076861](https://github.com/OXY2DEV/markview.nvim/assets/3357792/d321be60-d659-431b-97fe-581e1ca8f769)

It's worth noting closing nvim and loading the file again will display them in the correct position, so this bug only happens when leaving insert mode.
![screenshot_2024-07-09_13-42-17_988047156](https://github.com/OXY2DEV/markview.nvim/assets/3357792/54f8fcdf-d0da-44d9-9900-11bda9f140b2)

## How to reproduce
With the default config, paste the next text
```markdown
## TODO: XXX CUCUMBER
* [ ] Cucumber TDD file  →
  tests de comportamiento. Valida que el comportamiento de cada función que
  escribimos es correcto.  Para un alto coverage hay que cubrir todas
  las lineas.
* [ ] Cucumber ATDD file → tests de aceptación. Valida que los requisitos del
  progrma se cumplen. A menudo se escriben tras los tests de comportamiento.
  Son los e2e.
* [ ] Queremos que los requisitos que ya tenemos, emanen de un fichero
  cucumber (ej3 TDD).
* [ ] Igual para el ej 2 (ATDD).
```

**Comment by OXY2DEV** [comment]
Does it also occur if you switch to the `dev` branch?

I can't reproduce it.
![Screenshot_2024-07-09-17-54-09-295_com.termux-edit.jpg](https://github.com/OXY2DEV/markview.nvim/assets/122956967/b6962a3a-9ffd-4021-8cad-6ade9a98ff0d)

**Comment by Zeioth** [comment]
I'm gonna ensure no plugin is interfering with this one. Give me a little time to prepare a min file.

**Comment by Zeioth** [comment]
Ok this is indeed not an issue in markview. It is caused by the plugin.
https://github.com/petertriho/nvim-scrollbar

```lua
  {
    "petertriho/nvim-scrollbar",
     event = "VeryLazy",
     opts = {},
  },
```

The monkey patch is to just disable the plugin on markdown files and let markview do its thing:

```
  {
    "petertriho/nvim-scrollbar",
    opts = {
      excluded_filetypes = {
        "markdown",
        "cmp_docs",
        "cmp_menu",
        "noice",
        "prompt",
        "TelescopePrompt",
        "alpha",
      },
    },
  },
```

But I'll see if find a way to make both plugins coexist in peace.

**Comment by Zeioth** [comment]
The next defaults fix the issue.

```lua
  {
    "OXY2DEV/markview.nvim",
    ft = { "markdown" },
    dependencies = {
      "nvim-treesitter/nvim-treesitter",
      "nvim-tree/nvim-web-devicons"
    },
    opts = {
      headings = {
        shift_width = 0,
        heading_1 = {
          style = "label",
          sign = "",
          sign_hl = "MarkviewCol7Fg",
          hl = "MarkviewCol7Fg"
        },
        heading_2 = {
          style = "label",
          sign = "▶",
          sign_hl = "col_2_fg",
        },
        heading_3 = {
          style = "label",
          sign = "󰼑",
          sign_hl = "col_1_fg",
          hl = "MarkviewCol3",
        },
        heading_4 = {
          style = "label",
          sign = "󰎲",
          sign_hl = "col_1_fg",
          hl = "MarkviewCol4",
        },
        heading_5 = {
          style = "label",
          sign = "󰼓",
          sign_hl = "col_1_fg",
          hl = "MarkviewCol5",
        },
        heading_6 = {
          style = "label",
          sign = "󰎴",
          sign_hl = "col_1_fg",
          hl = "MarkviewCol6",
        }
      },
      list_items = {
        marker_minus = {
          add_padding = true,
          text = "",
          hl = "markviewCol2Fg"
        },
        marker_plus = {
          add_padding = true,
          text = "",
          hl = "markviewCol4Fg"
        },
        marker_star = {
          add_padding = true,
          text = "",
          text_hl = "markviewCol6Fg"
        },
        marker_dot = {
          add_padding = true
        },
      },
      block_quotes = {
        enable = true,
        default = { border = "▋", border_hl = "MarkviewCol7Fg" },
        callouts = {
          {
            match_string = "NOTE",
            callout_preview = "󰋽 Note",
            callout_preview_hl = "MarkviewCol4Fg",

            custom_title = true,
            custom_icon = "󰋽 ",

            border = "▋",
            border_hl = "MarkviewCol5Fg"
          },
          {
            match_string = "DESCRIPTION",
            callout_preview = "󰋽 DESCRIPTION",
            callout_preview_hl = "MarkviewCol7Fg",

            custom_title = true,
            custom_icon = "",

            border = "▋",
            border_hl = "MarkviewCol7Fg"
          },
          {
            match_string = "TODO",
            callout_preview = "󰋽 ",
            callout_preview_hl = "MarkviewCol4Fg",

            custom_title = true,
            custom_icon = "󰋽 ",

            border = "▋",
            border_hl = "MarkviewCol5Fg"
          },
          {
            match_string = "BUG",
            callout_preview = " Bug",
            callout_preview_hl = "MarkviewCol1Fg",

            custom_title = true,
            custom_icon = "  ",

            border = "▋",
            border_hl = "MarkviewCol1Fg"
          },
          {
            match_string = "EXAMPLE",
            callout_preview = "󱖫 Example",
            callout_preview_hl = "MarkviewCol6Fg",

            custom_title = true,
            custom_icon = "󱖫 ",

            border = "▋",
            border_hl = "MarkviewCol6Fg"
          },
          {
            match_string = "IMPORTANT",
            callout_preview = " Important",
            callout_preview_hl = "MarkviewCol3Fg",

            custom_title = true,
            custom_icon = " ",

            border = "▋",
            border_hl = "MarkviewCol3Fg"
          },
          {
            match_string = "WARNING",
            callout_preview = " Warning",
            callout_preview_hl = "MarkviewCol2Fg",

            custom_title = true,
            custom_icon = " ",

            border = "▋",
            border_hl = "MarkviewCol2Fg"
          },
        }
      },
      checkboxes = {
        checked = { text = "⚫", hl = "markviewCol4Fg" },
        pending = { text = "⭕", hl = "MarkviewCol2Fg" },
        unchecked = { text = "🟢", hl = "markviewCol1Fg" }
      },
      horizontal_rules = {
        parts = { {
          type = "repeating",
          text = "─",
          repeat_amount = function()
            return vim.o.colorcolumn - 1
          end,
        } },
      },
    }
  },
```

There seem to be a few element with padding issues atm. But with this config I can work for now.

![screenshot_2024-07-14_13-00-06_349806956](https://github.com/user-attachments/assets/ecad41c9-8e04-4057-aeae-91ec97fb0518)

![screenshot_2024-07-14_12-55-53_497480668](https://github.com/user-attachments/assets/89fd0f9f-a141-4545-b26e-7c2408636c70)

**Comment by OXY2DEV** [comment]
It should work like normal now.
