### ISSUE TITLE
[BUG]: Overriding `list_items` disable the whole feature

### ISSUE THREAD

**Issue by Zeioth** [OXY2DEV/markview.nvim#47]
## Config
* nvim version: 0.10
* theme: default (or any other)
* os: arch linux

```lua
  {
    "OXY2DEV/markview.nvim",
    ft = { "markdown" },
    dependencies = {
      "nvim-treesitter/nvim-treesitter",
      "nvim-tree/nvim-web-devicons"
    },
    opts = {
        list_items = {},
    }
  },
```

## What should happen
The default options are used, and we can override the option we want.

## What actually happen
The feature is disabled entirely, no matter the content of the list `list_items`

![screenshot_2024-07-09_14-04-27_134833917](https://github.com/OXY2DEV/markview.nvim/assets/3357792/84a43622-8d7d-4f2a-83cf-80a9cd9db3a7)

You can see no bullet points are displayed.

## How to reproduce
With the config above, paste the next text
```markdown
## TODO: XXX CUCUMBER
* [ ] Cucumber TDD file  →
  tests de comportamiento. Valida que el comportamiento de cada función que
  escribimos es correcto.  Para un alto coverage hay que cubrir todas
  las lineas.
* [ ] Cucumber ATDD file → tests de aceptación. Valida que los requisitos del
  progrma se cumplen. A menudo se escriben tras los tests de comportamiento.
  Son los e2e.
* [ ] Queremos que los requisitos que ya tenemos, emanen de un fichero
  cucumber (ej3 TDD).
* [ ] Igual para el ej 2 (ATDD).
```

**Comment by OXY2DEV** [comment]
This is intended.

It's to prevent cases where they only configured 1 list type but the other list types are also configured(which will be an unexpected behavior of the plugin).

You can always pull them the default options `require("markview").configuration` or from `require("markview.presets")` when that is available.

**Comment by OXY2DEV** [comment]
After testing out with `tbl_deep_extend` I have noticed that it unfortunately doesn't quite work well with `inline_codes`, `links`(specifically the options inside it) and a few others.

And honestly from a users perspective it would be very hard to tell what is adding things to their configuration table(and altering the end result).

Plus, the user will have to define all the options to something(as setting them to nil won't work).

So, this won't be added.
